-- MySQL Script generated by MySQL Workbench
-- Wed Feb  7 10:56:26 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema enaplo_sz1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema enaplo_sz1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `enaplo_sz1` DEFAULT CHARACTER SET utf8 ;
USE `enaplo_sz1` ;

-- -----------------------------------------------------
-- Table `enaplo_sz1`.`orarend`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enaplo_sz1`.`orarend` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `osztaly_id` INT NOT NULL,
  `datum` DATE NOT NULL,
  `ora_szama` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `enaplo_sz1`.`tanarok`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enaplo_sz1`.`tanarok` (
  `tanar_id` INT NOT NULL AUTO_INCREMENT,
  `nev` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tanar_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `enaplo_sz1`.`osztalyok`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enaplo_sz1`.`osztalyok` (
  `osztaly_id` INT NOT NULL AUTO_INCREMENT,
  `osztalyfonok_id` INT NOT NULL,
  `megnevezes` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`osztaly_id`),
  INDEX `fk_osztalyok_tanarok_idx` (`osztalyfonok_id` ASC) ,
  CONSTRAINT `fk_osztalyok_tanarok`
    FOREIGN KEY (`osztalyfonok_id`)
    REFERENCES `enaplo_sz1`.`tanarok` (`tanar_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `enaplo_sz1`.`diakok`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enaplo_sz1`.`diakok` (
  `oktazon` INT NOT NULL,
  `osztaly_id` INT NOT NULL,
  `nev` VARCHAR(45) NOT NULL,
  `szuldatum` DATE NOT NULL,
  `szulhely` VARCHAR(45) NOT NULL,
  `anyja_neve` VARCHAR(45) NOT NULL,
  `lakcim` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`oktazon`),
  INDEX `fk_diakok_osztalyok1_idx` (`osztaly_id` ASC) ,
  CONSTRAINT `fk_diakok_osztalyok1`
    FOREIGN KEY (`osztaly_id`)
    REFERENCES `enaplo_sz1`.`osztalyok` (`osztaly_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `enaplo_sz1`.`tantargyak`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enaplo_sz1`.`tantargyak` (
  `tantargy_id` INT NOT NULL,
  `megnevezes` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tantargy_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `enaplo_sz1`.`tanitott_tantargyak`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enaplo_sz1`.`tanitott_tantargyak` (
  `tanitott_id` INT NOT NULL,
  `tantargy_id` INT NOT NULL,
  `tanar_id` INT NOT NULL,
  PRIMARY KEY (`tanitott_id`),
  INDEX `fk_tanitott_tantargyak_tanarok1_idx` (`tanar_id` ASC) ,
  CONSTRAINT `fk_tanitott_tantargyak_tanarok1`
    FOREIGN KEY (`tanar_id`)
    REFERENCES `enaplo_sz1`.`tanarok` (`tanar_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `enaplo_sz1`.`tantargyak-tanitott_kapcs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enaplo_sz1`.`tantargyak-tanitott_kapcs` (
  `tantargyak_tantargy_id` INT NOT NULL,
  `tanitott_tantargyak_tanitott_id` INT NOT NULL,
  PRIMARY KEY (`tantargyak_tantargy_id`, `tanitott_tantargyak_tanitott_id`),
  INDEX `fk_tantargyak_has_tanitott_tantargyak_tanitott_tantargyak1_idx` (`tanitott_tantargyak_tanitott_id` ASC) ,
  INDEX `fk_tantargyak_has_tanitott_tantargyak_tantargyak1_idx` (`tantargyak_tantargy_id` ASC) ,
  CONSTRAINT `fk_tantargyak_has_tanitott_tantargyak_tantargyak1`
    FOREIGN KEY (`tantargyak_tantargy_id`)
    REFERENCES `enaplo_sz1`.`tantargyak` (`tantargy_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tantargyak_has_tanitott_tantargyak_tanitott_tantargyak1`
    FOREIGN KEY (`tanitott_tantargyak_tanitott_id`)
    REFERENCES `enaplo_sz1`.`tanitott_tantargyak` (`tanitott_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `enaplo_sz1`.`orarend-tanitott_kapcs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enaplo_sz1`.`orarend-tanitott_kapcs` (
  `orarend_id` INT NOT NULL,
  `tanitott_tantargyak_tanitott_id` INT NOT NULL,
  PRIMARY KEY (`orarend_id`, `tanitott_tantargyak_tanitott_id`),
  INDEX `fk_orarend_has_tanitott_tantargyak_tanitott_tantargyak1_idx` (`tanitott_tantargyak_tanitott_id` ASC) ,
  CONSTRAINT `fk_orarend_has_tanitott_tantargyak_orarend1`
    FOREIGN KEY (`orarend_id`)
    REFERENCES `enaplo_sz1`.`orarend` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orarend_has_tanitott_tantargyak_tanitott_tantargyak1`
    FOREIGN KEY (`tanitott_tantargyak_tanitott_id`)
    REFERENCES `enaplo_sz1`.`tanitott_tantargyak` (`tanitott_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
